services:
  - type: web
    name: miniCRM
    runtime: docker
    branch: main
    plan: starter
    dockerfilePath: Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://your-render-app.onrender.com"
      - key: DB_HOST
        fromDatabase:
          name: miniCRM-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: miniCRM-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: miniCRM-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: miniCRM-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: miniCRM-db
          property: database
      - key: REDIS_HOST
        value: "<PUT_REDIS_HOST>"
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

databases:
  - name: miniCRM-db
    postgresMajorVersion: "18"
    databaseName: minicrm
